export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_PRESENT = "USER_PRESENT";

export const GET_MENS_REQUEST = "GET_MENS_REQUEST";
export const GET_MENS_DATA = "GET_MENS_DATA";
export const GET_ALL_MENS_DATA = "GET_ALL_MENS_DATA";
export const GET_MENS_ERROR = "GET_MENS_ERROR";

export const GET_WOMENS_REQUEST = "GET_WOMENS_REQUEST";
export const GET_WOMENS_DATA = "GET_WOMENS_DATA";
export const GET_ALL_WOMENS_DATA = "GET_ALL_WOMENS_DATA";
export const GET_WOMENS_ERROR = "GET_WOMENS_ERROR";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

export const GET_FROM_CART_REQUEST = "GET_FROM_CART_REQUEST";
export const GET_FROM_CART_SUCCESS = "GET_FROM_CART_SUCCESS";
export const GET_FROM_CART_ERROR = "GET_FROM_CART_ERROR";

export const DELETE_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST";
export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_ERROR = "DELETE_FROM_CART_ERROR";

export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST"; 
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_ERROR = "ADD_TO_WISHLIST_ERROR";

export const GET_FROM_WISHLIST_REQUEST = "GET_FROM_WISHLIST_REQUEST";
export const GET_FROM_WISHLIST_SUCCESS = "GET_FROM_WISHLIST_SUCCESS";
export const GET_FROM_WISHLIST_ERROR = "GET_FROM_WISHLIST_ERROR";

export const DELETE_FROM_WISHLIST_REQUEST = "DELETE_FROM_WISHLIST_REQUEST";
export const DELETE_FROM_WISHLIST_SUCCESS = "DELETE_FROM_WISHLIST_SUCCESS";
export const DELETE_FROM_WISHLIST_ERROR = "DELETE_FROM_WISHLIST_ERROR";
